### ISSUE TITLE
ValueError invalid literal for int() with base 10 when reading partition list

### ISSUE THREAD

**Issue by tr4nt0r** [petersulyok/diskinfo#6]
I am getting this error when trying to list the partitions of an NTFS formatted Disk:

```
Traceback (most recent call last):
  File "/usr/local/bin/disklist.py", line 15, in <module>
    plist = d.get_partition_list()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/diskinfo/disk.py", line 825, in get_partition_list
    result.append(Partition(os.path.basename(path), _read_file(path + "/dev")))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/diskinfo/partition.py", line 116, in __init__
    self.__part_number = int(_read_udev_property(path, "ID_PART_ENTRY_NUMBER="))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

This is the fdisk output of the drive that causes the error:

```
Disk /dev/sdb: 2.73 TiB, 3000592982016 bytes, 732566646 sectors
Disk model: USB 3.0 Device  
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x3e8d79b9

Device     Boot Start       End   Sectors  Size Id Type
/dev/sdb1          63 732563999 732563937  2.7T  7 HPFS/NTFS/exFAT

```

**Comment by petersulyok** [comment]
Hi @tr4nt0r, thanks for reporting this issue.
Could you please copy the content of the file `/run/udev/data/b8:17` into this chat?

**Comment by tr4nt0r** [comment]
```
S:disk/by-label/HDD
S:disk/by-id/usb-Intenso_USB_3.0_Device_30900000000000003E5E-0:0-part1
S:disk/by-path/platform-xhci-hcd.1-usb-0:1:1.0-scsi-0:0:0:0-part1
S:disk/by-id/ata-ST3000DM001-1CH166_Z1F2F7FC-part1
S:disk/by-uuid/01D2B7812DAE5670
S:disk/by-id/wwn-0x5000c5004fec4a91-part1
I:1642359603659
E:ID_ATA=1
E:ID_TYPE=disk
E:ID_BUS=ata
E:ID_MODEL=ST3000DM001-1CH166
E:ID_MODEL_ENC=ST3000DM001-1CH166\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E:ID_REVISION=CC44
E:ID_SERIAL=ST3000DM001-1CH166_Z1F2F7FC
E:ID_SERIAL_SHORT=Z1F2F7FC
E:ID_ATA_WRITE_CACHE=1
E:ID_ATA_WRITE_CACHE_ENABLED=1
E:ID_ATA_FEATURE_SET_HPA=1
E:ID_ATA_FEATURE_SET_HPA_ENABLED=1
E:ID_ATA_FEATURE_SET_PM=1
E:ID_ATA_FEATURE_SET_PM_ENABLED=1
E:ID_ATA_FEATURE_SET_SECURITY=1
E:ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E:ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=334
E:ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=334
E:ID_ATA_FEATURE_SET_SMART=1
E:ID_ATA_FEATURE_SET_SMART_ENABLED=1
E:ID_ATA_FEATURE_SET_APM=1
E:ID_ATA_FEATURE_SET_APM_ENABLED=1
E:ID_ATA_FEATURE_SET_APM_CURRENT_VALUE=128
E:ID_ATA_DOWNLOAD_MICROCODE=1
E:ID_ATA_SATA=1
E:ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E:ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E:ID_ATA_ROTATION_RATE_RPM=7200
E:ID_WWN=0x5000c5004fec4a91
E:ID_WWN_WITH_EXTENSION=0x5000c5004fec4a91
E:ID_USB_MODEL=USB_3.0_Device
E:ID_USB_MODEL_ENC=USB\x203.0\x20Device\x20\x20
E:ID_USB_MODEL_ID=55aa
E:ID_USB_SERIAL=Intenso_USB_3.0_Device_30900000000000003E5E-0:0
E:ID_USB_SERIAL_SHORT=30900000000000003E5E
E:ID_USB_VENDOR=Intenso
E:ID_USB_VENDOR_ENC=Intenso\x20
E:ID_USB_VENDOR_ID=174c
E:ID_USB_REVISION=CC44
E:ID_USB_TYPE=disk
E:ID_USB_INSTANCE=0:0
E:ID_USB_INTERFACES=:080650:
E:ID_USB_INTERFACE_NUM=00
E:ID_USB_DRIVER=usb-storage
E:ID_PATH=platform-xhci-hcd.1-usb-0:1:1.0-scsi-0:0:0:0
E:ID_PATH_TAG=platform-xhci-hcd_1-usb-0_1_1_0-scsi-0_0_0_0
E:ID_PART_TABLE_UUID=3e8d79b9
E:ID_PART_TABLE_TYPE=dos
E:ID_FS_LABEL=HDD
E:ID_FS_LABEL_ENC=HDD
E:ID_FS_UUID=01D2B7812DAE5670
E:ID_FS_UUID_ENC=01D2B7812DAE5670
E:ID_FS_TYPE=ntfs
E:ID_FS_USAGE=filesystem
G:systemd
Q:systemd
V:1

```

**Comment by petersulyok** [comment]
Could please check if version **v3.1.1** is fixing the assertion?
Based on the file you shared I have to say the partition information (e.g. number, offset and size) is missing in your case. 
Here is a sample for a gpt partition:

```
...
E:ID_PART_ENTRY_SCHEME=gpt
E:ID_PART_ENTRY_NAME=Basic\x20data\x20partition
E:ID_PART_ENTRY_UUID=0df2fd96-5385-40b6-bd43-eeae37ba9c91
E:ID_PART_ENTRY_TYPE=ebd0a0a2-b9e5-4433-87c0-68b6b72699c7
E:ID_PART_ENTRY_NUMBER=1
E:ID_PART_ENTRY_OFFSET=2048
E:ID_PART_ENTRY_SIZE=3907026944
E:ID_PART_ENTRY_DISK=8:16
...
```

How/where did you format this? I assume this is an old MBR partition table, right?

**Comment by tr4nt0r** [comment]
Works like a charm now, thanks. And yes, it is an MBR partition table. I bought this USB disk in 2013 and i think i never re-partitioned or formatted it since.
